# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 00:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickBudget', '0002_auto_20170220_0057'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sample',
            new_name='SampleModel',
        ),
    ]
